project_id = "ctwvbnalunqsydacbekg"

[functions.business-assistant]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false

[functions.propostas-analisar-template]
verify_jwt = true

[functions.propostas-sugerir-config]
verify_jwt = true

[functions.propostas-ajustar-texto]
verify_jwt = true

[functions.propostas-analisar-template-blocos]
verify_jwt = true

[functions.propostas-gerar-proposta]
verify_jwt = true

[functions.propostas-detectar-produtos]
verify_jwt = true

[functions.propostas-gerar-contexto]
verify_jwt = true

[functions.propostas-conversacional]
verify_jwt = true
